const AllDataTypesInJs = {
    string: '',
    number: 0,
    boolean: false,
    null: null,
    undefined: undefined,
    object: {},
    array: [],
    function: function() {},
    setString: function(value) { this.string = value; },
    getString: function() { return this.string; },
    setNumber: function(value) { this.number = value; },
    getNumber: function() { return this.number; },
    setBoolean: function(value) { this.boolean = value; },
    getBoolean: function() { return this.boolean; },
    setNull: function(value) { this.null = value; },
    getNull: function() { return this.null; },
    setUndefined: function(value) { this.undefined = value; },
    getUndefined: function() { return this.undefined; },
    setObject: function(value) { this.object = value; },
    getObject: function() { return this.object; },
    setArray: function(value) { this.array = value; },
    getArray: function() { return this.array; },
    setFunction: function(value) { this.function = value; },
    getFunction: function() { return this.function; }
};
